image: .NET Core 3.0.0-preview-27122-01

build_script:
  - dotnet build -c release

test_script:
  - cd MarbleTest.Net.Test
  - dotnet test

after_build:
  - dotnet publish MarbleTest.Net -c release -o %appveyor_build_folder%\dist
