image: .NET Core 2.2.4 runtime

build_script:
  - dotnet build -c release

test_script:
  - cd MarbleTest.Net.Test
  - dotnet test

after_build:
  - dotnet publish MarbleTest.Net -c release -o %appveyor_build_folder%\dist
